auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.createListing, name="create"),
    path("displayCategory", views.displayCategory, name="displayCategory"),
    path("listing/<int:id>", views.listing, name="listing"),
    path("removeWatchlist/<int:id>", views.removeWatchlist, name="removeWatchlist"),
    path("addWatchlist/<int:id>", views.addWatchlist, name="addWatchlist"),
    path("watchlist", views.displayWatchlist, name="watchlist"),
    path("addComment/<int:id>", views.addComment, name="addComment"),
    path("addBid/<int:id>", views.addBid, name="addBid"),
    path("closeAuction/<int:id>", views.closeAuction, name="closeAuction"),
    path('my-listings/', views.my_listings, name='my_listings'),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    # path('', include('admin_volt.urls')),
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Category(models.Model):
    categoryName = models.CharField(max_length=50)

    def __str__(self):
        return f"Category: {self.categoryName}"

class Bid(models.Model):
    bid = models.FloatField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="userBid")

    def __str__(self):
        return str(self.bid)


class Listing(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    imageUrl = models.ImageField(upload_to='images/commerce/', blank=True, default='default_image_url')
    price = models.ForeignKey(Bid, on_delete=models.CASCADE, blank=True, null=True, related_name="bidPrice")
    isActive = models.BooleanField(default=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="user")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True, related_name="category")
    watchlist = models.ManyToManyField(User, blank=True, null=True, related_name="listingWatchlist")

    def __str__(self):
        return f"The title of the song: {self.title} - and is a: {self.category.categoryName}"
    
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="userComment")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, blank=True, null=True, related_name="listingComment")
    message = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.author} commented on {self.listing}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .form import ListingForm
from django.contrib import messages
from .models import Listing, User, Category, Comment, Bid
from django.db.models import F
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

def listing(request, id):
    listing_data = Listing.objects.get(pk=id)
    isListingInWatchlist = request.user in listing_data.watchlist.all()
    allComments = Comment.objects.filter(listing=listing_data)
    isOwner = request.user.username == listing_data.owner.username 
    return render(request, "auctions/listing.html", {
        "listing": listing_data,
        "isListingInWatchlist": isListingInWatchlist,
        "allComments": allComments,
        "isOwner": isOwner,
    })

def my_listings(request):
    user_winning_listings = Listing.objects.filter(price__user=request.user, price__bid=F('price__bid'))
    page_number = request.GET.get('page', 1)
    items_per_page = 5
    paginator = Paginator(user_winning_listings, items_per_page)
    page = paginator.get_page(page_number)
    
    return render(request, "auctions/my_listings.html", {
        "user_winning_listings": page,
    })

def closeAuction(request, id):
    listingData = Listing.objects.get(pk=id)
    listingData.isActive = False
    listingData.save()
    isOwner = request.user.username == listingData.owner.username 
    isListingInWatchlist = request.user in listingData.watchlist.all()
    allComments = Comment.objects.filter(listing=listingData)
    return render(request, "auctions/listing.html", {
        "listing": listingData,
        "isListingInWatchlist": isListingInWatchlist,
        "allComments": allComments,
        "isOwner": isOwner,
        "update": True,
        "message": "Congratulations! Your auction is closed."
    })


def addComment(request, id):
    currentUser = request.user
    listingData = Listing.objects.get(pk=id)
    message = request.POST['comment']

    newComment = Comment(
        author = currentUser,
        listing = listingData,
        message = message,
    )

    newComment.save()
    return HttpResponseRedirect(reverse("listing",args=(id, )))


def addBid(request, id):
    newBid = request.POST['newBid']
    listingData = Listing.objects.get(pk=id)
    isListingInWatchlist = request.user in listingData.watchlist.all()
    allComments = Comment.objects.filter(listing=listingData)
    isOwner = request.user.username == listingData.owner.username 
    if int(newBid) > listingData.price.bid:
        updateBid = Bid(user=request.user, bid=int(newBid))
        updateBid.save()
        listingData.price = updateBid
        listingData.save()
        success_message = "Bid was updated successfully"
        return render(request, "auctions/listing.html",{
            "listing": listingData,
            "success_message": success_message,
            "update": True,
            "isListingInWatchlist": isListingInWatchlist,
            "allComments": allComments,
            "isOwner": isOwner,
        })
    else:
        error_message = "Bid update failed. Your bid should be higher than the current highest bid."
        return render(request, "auctions/listing.html",{
            "listing": listingData,
            "error_message": error_message,
            "update": False,
            "isListingInWatchlist": isListingInWatchlist,
            "allComments": allComments,
            "isOwner": isOwner,
        })

    
def displayWatchlist(request):
    currentUser = request.user
    listings = currentUser.listingWatchlist.all()
    items_per_page = 5
    paginator = Paginator(listings, items_per_page)
    page_number = request.GET.get('page')
    page_listings = paginator.get_page(page_number)
    return render(request, "auctions/watchlist.html",{
        "listings": page_listings
    })

def removeWatchlist(request, id):
    listingData = Listing.objects.get(pk=id)
    currentUser = request.user
    listingData.watchlist.remove(currentUser)
    return HttpResponseRedirect(reverse("listing",args=(id, )))


def addWatchlist(request, id):
    listingData = Listing.objects.get(pk=id)
    currentUser = request.user
    listingData.watchlist.add(currentUser)
    return HttpResponseRedirect(reverse("listing",args=(id, )))


def index(request):
    listings = Listing.objects.filter(isActive=True)
    paginator = Paginator(listings, 5)
    page_number = request.GET.get('page')
    page_listings = paginator.get_page(page_number)

    allCategories = Category.objects.all()
    return render(request, "auctions/index.html", {
        "listings": page_listings,
        "categories": allCategories,
    })

def displayCategory(request):
    if request.method == "POST":
        category_id = request.POST.get('category')
        try:
            category = get_object_or_404(Category, pk=category_id)
        except Category.DoesNotExist:
            return HttpResponse("Not Found")
        else:
            activeListings = Listing.objects.filter(isActive=True, category=category)
            paginator = Paginator(activeListings, 5)
            page_number = request.GET.get('page')
            page_listings = paginator.get_page(page_number)
            allCategories = Category.objects.all()
            return render(request, "auctions/index.html", {
                "listings": page_listings,
                "categories": allCategories,
            })
    else:
        return redirect('index')

def createListing(request):
    if request.method == "POST":
        form = ListingForm(request.POST, request.FILES)
        if form.is_valid():
            listing = form.save(commit=False)
            listing.owner = request.user
            listing.save()

            custom_price = form.cleaned_data.get('custom_price')
            if custom_price is not None:
                existing_bid = Bid.objects.filter(bid=custom_price, user=request.user).first()
                if existing_bid:
                    listing.price = existing_bid
                else:
                    bid = Bid.objects.create(bid=custom_price, user=request.user)
                    bid.save()
                    listing.price = bid

                listing.save()

            messages.success(request, "New listing added successfully!")
            return redirect('index')
        else:
            messages.error(request, "Critical error")
    else:
        form = ListingForm()
        listings = Listing.objects.all()
        allCategories = Category.objects.all()
    context = {
        'form': form,
        'listings': listings,
        "allCategories": allCategories,
    }
    return render(request, "auctions/create.html", context)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container text-center tm-welcome-container">
  <div class="tm-welcome">
    <i class="fas tm-fa-big fa-music tm-fa-mb-big"></i>
    <h1 class="text-uppercase mb-3 tm-site-name">Commerce</h1>
    <p class="tm-site-description">Add a new listing</p>
  </div>
</div>

</div>

<form method="post" enctype="multipart/form-data" class="mt-4 mb-4">
  {% csrf_token %}
  <div class="mb-3">
    <label for="id_title" class="form-label h4">Title:</label>
    <input type="text" name="title" maxlength="50" required class="form-control" id="id_title">
  </div>

  <div class="mb-3">
    <label for="id_description" class="form-label h4">Description:</label>
    <input type="text" name="description" maxlength="100" required class="form-control" id="id_description">
  </div>

  <div class="mb-3">
    <label for="id_imageUrl" class="form-label h4">Image:</label>
    <input required type="file" name="imageUrl" accept="image/*" class="form-control" id="id_imageUrl">
  </div>

  <div class="mb-3">
    <label for="id_price" class="form-label h4">Price:</label>
    <input type="number" min="0" name="custom_price" step="any" required class="form-control" id="id_price">
  </div>

  <div class="mb-3">
    <label for="id_category" class="form-label h4">Category:</label>
    <select required name="category" class="form-select" id="id_category">
      <option value="" selected>---------</option>
      {% for catego in allCategories %}
      <option value="{{ catego.id }}">Category: {{ catego.categoryName }}</option>
      {% endfor %}
    </select>
  </div>

  <div class="text-end">
    <button type="submit" class="btn btn-primary">Create Listing</button>
  </div>
</form>



{% if form.errors %}
<div class="errors">
  <h3>Errors in the form:</h3>
  <ul>
    {% for field in form %}
    {% if field.errors %}
    <li>{{ field.label }}: {{ field.errors|join:", " }}</li>
    {% endif %}
    {% endfor %}
  </ul>
</div>
{% endif %}

{% endblock %}

auctions/templates/auctions/email_template.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ subject }}</title>
</head>
<body>
    <h1>{{ subject }}</h1>
    <p>{{ message }}</p>
    <p>Thank you for using our auction platform!</p>
</body>
</html>

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

{% load static %}



<div class="container text-center tm-welcome-container">
  <div class="tm-welcome">
    <i class="fas tm-fa-big fa-music tm-fa-mb-big"></i>
    <h1 class="text-uppercase mb-3 tm-site-name">Commerce</h1>
    <p class="tm-site-description">Active Listings</p>
  </div>
</div>

</div>

<div class="container">




  <div class="row">
    <div class="col-lg-12">
      <div class="tm-tag-line">
        <h2 class="tm-tag-line-title">Music is your powerful energy.</h2>
      </div>
    </div>
  </div>

  <form action="{% url 'displayCategory' %}" method="post" class="d-flex align-items-center justify-content-end">
    {% csrf_token %}
    <div class="form-group mb-0 me-2">
      <label for="category" class="mb-0">Choose a category:</label>
      <select required name="category" class="form-select" id="category">
        <option value="" selected>---------</option>
        {% for catego in categories %}
        <option value="{{ catego.id }}">{{ catego.categoryName }}</option>
        {% endfor %}
      </select>
    </div>
    <button type="submit" class="btn btn-warning" style="background-color: #6699cc; border-color: #6699cc; color: white;">Select</button>
  </form>
  

  <div class="mt-4">
  </div>

  <div class="row mb-5">
    <div class="col-xl-12">
      <div class="media-boxes">
        {% for listing in listings %}
        <div class="media">
          <img src="{{ listing.imageUrl.url }}" alt="Image" class="custom-small-image">
          <style>
            .custom-small-image {
              width: 140px;
              height: 140px;
              object-fit: cover;
            }
          </style>
          <div class="media-body tm-bg-gray">
            <div class="tm-description-box">
              <h5 class="tm-text-blue">{{ listing.title }} - {{ listing.category.categoryName }}</h5>
              <p class="mb-0">{{ listing.description }}</p>
            </div>
            <div class="tm-buy-box">
              <a href="{% url 'listing' id=listing.id %}" class="tm-bg-blue tm-text-white tm-buy">See details</a>
              <span class="tm-text-blue tm-price-tag">${{ listing.price }}</span>
            </div>
          </div>
        </div>
        {% endfor %}

        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">
            {% if listings.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                  <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ listings.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {% endif %}
        
            <li class="page-item disabled">
              <span class="page-link">Page {{ listings.number }} of {{ listings.paginator.num_pages }}</span>
            </li>
        
            {% if listings.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ listings.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ listings.paginator.num_pages }}" aria-label="Last">
                  <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
        

      </div> <!-- media-boxes -->
    </div>
  </div>


 
</div> <!-- .container -->

</div> <!-- .main -->
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
/>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
    <!-- <link href="{% static 'auctions/styles.css' %}" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- <link href="{% static 'auctions/sty.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'assets/icos/note_audio_music_3097.ico' %}" type="image/x-icon"> -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        var renderPage = true;

        if (navigator.userAgent.indexOf('MSIE') !== -1
            || navigator.appVersion.indexOf('Trident/') > 0) {
            alert("Please view this in a modern browser such as Chrome or Microsoft Edge.");
            renderPage = false;
        }
    </script>
</head>

<body>
    <!-- Loader -->
  <div id="loader-wrapper">
    <!-- <div id="loader"></div> -->
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
  </div>

  <div class="tm-main">

    

    <div class="tm-welcome-section">
      <div class="container tm-navbar-container">
        <div class="row">
          <div class="col-xl-12">
            <nav class="navbar navbar-expand-sm">
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a href="" class="nav-link tm-nav-link tm-text-white">{{ user.username }}</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a href="" class="nav-link tm-nav-link tm-text-white"> Not signed in.</a>
                </li>
                {% endif %}
                <li class="nav-item">
                  <a href="{% url 'index' %}" class="nav-link tm-nav-link tm-text-white">Active Listing</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'create' %}" class="nav-link tm-nav-link tm-text-white">Create a new Listing</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'watchlist' %}" class="nav-link tm-nav-link tm-text-white">Watchlist</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'my_listings' %}" class="nav-link tm-nav-link tm-text-white">My listings</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'logout' %}" class="nav-link tm-nav-link tm-text-white">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a href="{% url 'login' %}" class="nav-link tm-nav-link tm-text-white">Log In</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'register' %}" class="nav-link tm-nav-link tm-text-white">Register</a>
                </li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
    
  

      {% block body %}
        {% endblock %}


  <!-- load JS -->
  <script src="{% static 'scripts/jquery-3.2.1.slim.min.js' %}"></script>
  <script>
    $(function () {

      if (renderPage) {
        $('body').addClass('loaded');
      }

      $('.tm-current-year').text(new Date().getFullYear());
    });

  </script>
</body>

</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container mt-4">
  <div class="row mt-4">
    {% if user.is_authenticated and listing.isActive %}
    {% if isOwner %}
    <form action="{% url 'closeAuction' id=listing.id %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Close auction</button>
    </form>
    {% endif %}
    <div class="mt-4"></div>
    {% if isListingInWatchlist %}
    <form action="{% url 'removeWatchlist' id=listing.id %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Remove from Watchlist</button>
    </form>
    {% else %}
    <form action="{% url 'addWatchlist' id=listing.id %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-success">Add to Watchlist</button>
    </form>
    {% endif %}
    {% endif %}
  </div>

  <br>
  <div class="row">
    <div class="col-md-4">
      <img src="{{ listing.imageUrl.url }}" alt="{{ listing.title }}" class="img-fluid custom-small-image">
      <style>
        .custom-small-image {
          width: 600px;
          height: 400px;
          object-fit: cover;
        }
      </style>
    </div>
    <div class="col-md-8">
      <h2>{{ listing.title }}</h2>
      <p>{{ listing.description }}</p>
      <p>Owner:&nbsp;{{ listing.owner }}</p>
      <p>Current price:&nbsp;{{ listing.price.bid }}&nbsp;$</p>
      {% if user.is_authenticated %}
      <form action="{% url 'addBid' id=listing.id %}" method="post" class="mt-3">
        {% csrf_token %}
        <div class="row gx-2">
          <div class="col-auto">
            <label for="price" class="form-label h4">Add Bid</label>
          </div>
          <div class="col-auto">
            <input type="number" min="0" name="newBid" class="form-control form-control-sm" placeholder="Add a new bid">
          </div>
          <div class="col-auto">
            <button type="submit" class="btn btn-primary">Add</button>
          </div>
        </div>
      </form>
      {% else %}
      <div class="row gx-2">
        <div class="col-auto">
          <label for="price" class="form-label h4">To be able to bid <a href="{% url 'login' %}"
              class="nav-link tm-nav-link tm-text-white">Login here!</a></label>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>

</div>
</div>



{% if success_message %}
<script>
  const SuccessToast = Swal.mixin({
    toast: true,
    position: 'top-end',
    showConfirmButton: false,
    timer: 3000,
    timerProgressBar: true,
    didOpen: (toast) => {
      toast.addEventListener('mouseenter', Swal.stopTimer);
      toast.addEventListener('mouseleave', Swal.resumeTimer);
    }
  });

  SuccessToast.fire({
    icon: 'success',
    title: '{{ success_message }}'
  });
</script>
{% endif %}

{% if error_message %}
<script>
  const ErrorToast = Swal.mixin({
    toast: true,
    position: 'top-end',
    showConfirmButton: false,
    timer: 3000,
    timerProgressBar: true,
    didOpen: (toast) => {
      toast.addEventListener('mouseenter', Swal.stopTimer);
      toast.addEventListener('mouseleave', Swal.resumeTimer);
    }
  });

  ErrorToast.fire({
    icon: 'error',
    title: '{{ error_message }}'
  });
</script>
{% endif %}

{% if message %}
<script>
const Toast = Swal.mixin({
  toast: true,
  position: 'top-end',
  showConfirmButton: false,
  timer: 3000,
  timerProgressBar: true,
  didOpen: (toast) => {
    toast.addEventListener('mouseenter', Swal.stopTimer);
    toast.addEventListener('mouseleave', Swal.resumeTimer);
  }
});

let message = '{{ message }}';

{% if listing.isActive and user == listing.price.user %}
message = "Congratulations! Your auction is closed and you are the highest bidder.";
{% endif %}

Toast.fire({
  icon: 'success',
  title: message
});
</script>
{% endif %}



<div class="mt-4">
</div>

<div class="row mx-5 text-center">
  <h2>Comments</h2>
  <br>
  {% if user.is_authenticated %}
  <form action="{% url 'addComment' id=listing.id %}" method="post" class="mt-3">
    {% csrf_token %}
    <div class="input-group">
      <input type="text" name="comment" class="form-control" placeholder="Add a new comment"
        aria-label="Add a new comment" required>
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
  {% endif %}
</div>
<br>
<br>
<br>
<div class="mt-4">
</div>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Comments</h5>
          <ul class="list-unstyled">
            {% for comment in allComments %}
            <li class="media mb-4">
              <img src="https://ui-avatars.com/api/?name={{ comment.author.username }}&color=7F9CF5&background=EBF4FF"
                alt="User Avatar" class="mr-3 rounded-circle" width="50">
              <div class="media-body" style="margin-right: 80px;">
                <h6 class="mt-0">{{ comment.author.username }}:&nbsp;</h6>
                <p>{{ comment.message }}</p>
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="mt-4">
</div>
<div class="mt-4">
</div>

{% endblock %}

auctions/templates/auctions/my_listings.html
{% extends "auctions/layout.html" %}

{% block body %}
</div>
</div>
    <h1>My Winning Listings</h1>

    <div class="row mb-5">
        <div class="col-xl-12">
          <div class="media-boxes">
            {% for listing in user_winning_listings %}
            <div class="media">
              <img src="{{ listing.imageUrl.url }}" alt="Image" class="custom-small-image">
              <style>
                .custom-small-image {
                  width: 140px;
                  height: 140px;
                  object-fit: cover;
                }
              </style>
              <div class="media-body tm-bg-gray">
                <div class="tm-description-box">
                  <h5 class="tm-text-blue">{{ listing.title }} - {{ listing.category.categoryName }}</h5>
                  <p class="mb-0">{{ listing.description }}</p>
                </div>
                <div class="tm-buy-box">
                  <a href="{% url 'listing' id=listing.id %}" class="tm-bg-blue tm-text-white tm-buy">Details</a>
                  <span class="tm-text-blue tm-price-tag">${{ listing.price.bid }}</span>
                </div>
              </div>
            </div>
            {% endfor %}
      
            
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if user_winning_listings.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo;&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ user_winning_listings.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
            
                    <li class="page-item disabled">
                        <span class="page-link">Página {{ user_winning_listings.number }} de {{ user_winning_listings.paginator.num_pages }}</span>
                    </li>
            
                    {% if user_winning_listings.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ user_winning_listings.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ user_winning_listings.paginator.num_pages }}" aria-label="Last">
                                <span aria-hidden="true">&raquo;&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            

          </div> <!-- media-boxes -->
        </div>
      </div>
      



{% endblock %}